# Generated by Django 6.0.3 on 2026-03-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinderRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_version', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('run_datetime', models.DateTimeField(auto_now_add=True)),
                ('hardware', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('gene_name', models.CharField(blank=True, max_length=255, null=True)),
                ('protein_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.TextField()),
                ('length', models.PositiveBigIntegerField(blank=True, null=True)),
                ('organism', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Binder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binder_sequence', models.TextField()),
                ('binder_length', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binderbase.binderrun')),
            ],
        ),
        migrations.AddField(
            model_name='binderrun',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binderbase.protein'),
        ),
    ]
