# Generated by Django 6.0.3 on 2026-03-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binderbase', '0002_binder_cif_path_binder_design_to_target_iptm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binderrun',
            name='run_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
