# Generated by Django 6.0.3 on 2026-03-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binderbase', '0003_alter_binderrun_run_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binder',
            name='cif_path',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='', verbose_name='CIF path'),
        ),
        migrations.AlterField(
            model_name='binderrun',
            name='cif_path',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='', verbose_name='CIF path'),
        ),
    ]
