# Generated by Django 6.0.3 on 2026-04-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binderbase', '0004_alter_binder_cif_path_alter_binderrun_cif_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binder',
            options={'ordering': ['run', 'final_rank']},
        ),
        migrations.AlterModelOptions(
            name='binderrun',
            options={'ordering': ['-run_datetime']},
        ),
        migrations.AddField(
            model_name='protein',
            name='biological_function',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='cif_path',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='', verbose_name='AlphaFold CIF path'),
        ),
        migrations.AddField(
            model_name='protein',
            name='pae_json_path',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='', verbose_name='PAE JSON path'),
        ),
    ]
